### PR TITLE
Add .de i18n

### PR DESCRIPTION
**Pull request by ofa-**

### CODE REVIEW

**Comment by jeevatkm** [comment]
@ofa- Thanks for adding German locale. Merging it.

**Comment by ofa-** [comment]
@jeevatkm oops, my bad, copy/paste error in ee21e51 => `"cc": { "de": "Cc:" }`
will push fix on my branch i.e. this PR :)

What happens if you --amend + push force your last squash-merge on your master ?

**Comment by ofa-** [comment]
ah, PR closed = no more updates.  Here is the patch:

```
commit 3adb24deaa93f68d68c12667caa66cf4641da56e
Author: ofa- <ofa@github>
Date:   Sun Feb 25 10:01:29 2018 +0100

    fix .de "cc" i18n:ed label

diff --git a/content/rwh.js b/content/rwh.js
index 9bd6f7d..9eee99d 100644
--- a/content/rwh.js
+++ b/content/rwh.js
@@ -997,7 +997,7 @@ var i18n = {
   "cc": {
     "en": "Cc:",
     "fr": "Cc :",
-    "de": "De :",
+    "de": "Cc:",
   },
   "subject": {
     "en": "Subject:",
```

**Comment by ofa-** [comment]
additional fix (thanks Wendelin) in new PR #43

**Comment by princemichi** [comment]
Thank you very much! When is the new release?

**Pull request merged**
