### PR TITLE
Add tz-adjuster support

### PR DESCRIPTION
**Pull request by ofa-**
This PR adds support for an (optional) timezone offset specification for each author in
Prefs > Misc > Date source > Use received date instead of sender's  [list of authors].

User story
--------------
When "Prefs > Misc > Date source > Use sender's date" is enabled and the author is not in [list of authors], RWH blindly uses the sender's date in the message.  The timezone info in there is however sometimes irrelevant, causing the reply header to display a valid sender's date, but with irrelevant, miss-leading timezone offset.  To fix this, the correct timezone offset needs to be provided on a per-author basis.

List entries in [list of authors] currently consist of simple author email matcher-regexps,
as on line 3 in table below. This PR adds support for entries of the form `author => [+-]xxxx`

List entry                              |  Effect
-----------------------------------   |  ---------
author_in_Japan => +0900  |    use `sender's date`  and adjust tz to +0900 (JST)
author_in_L.A.  => -0700     |    use `sender's date` and adjust tz to -0700 (PDT)
some_author                        |    use `received date` (thus local timezone).

Example
------------
Date source                |  Date value
---------------------          |  --------
received (local) date   |  12:03:00 +0100
sender (mime) date    |  11:00:00 +0000

Prefs > Misc > Date source > Use sender's date = checked

Prefs > Misc > Date source [list of authors]   |   Date shown in rwh header
------------------------------------                            |   ------------------------------------
author __not__ in list                                      |     11:00 +0000   `[sender's date]`
author in list (name only, no tz adjustment)                           |     12:03 +0100  `[received date]`
author in list, with " => +0900" adjustment     |     18:00 +0900  `[adjusted sender's date]`

Background
----------------
The sender's date (MIME date) is usually set correctly by email agents, however some provide no relevant timezone (tz) information.  For instance outlook.com sets the tz offset to +0000 irrespective of the effective user's timezone;  some iPhones set it to +0000 when not localised with the GPS;  some ticketing systems send mails on behalf of users with whatever tz is configured on the server.

### CODE REVIEW

**Comment by ofa-** [comment]
added further documentation for the tz-adjustment feature - also describe the problematics

now looks it would be simpler to just discard the "use received date" alternative
and rely only on the tz adjustment specification.

@jeevatkm what do you think ?

**Comment by ofa-** [comment]
@jeevatkm I am not aware of any built-in - or even plugin-based - support for multi-tz contacts management, and this is what this PR is about.  On the ease of use side, the PR adds optional, internal support for this feature without changing the existing settings / user inputs.

**Comment by ofa-** [comment]
@jeevatkm you could consider this PR is an Easter egg?

**Comment by jeevatkm** [comment]
@ofa- Sorry for the delay, I'm merging it. 

I was occupied with my another OpenSource project (https://aahframework.org), it got released on Mar 28, 2018. Also soon I will be start working towards RWH v2.0 release.

**Pull request merged**
