### PR TITLE
Whitespace commits

### PR DESCRIPTION
**Pull request by ofa-**
- fix whistpaces introduced in 4d42e93
- fix dos-file format (^M spotted in 1334f5c)

### CODE REVIEW

**Comment by ofa-** [comment]
Hi @jeevatkm thanks for merging this PR.

Are you doing squash-merge and/or post-editing the commits somehow ?  I see the original commit messages are lost, and author is turned into `ofa- <ofa@github>`.  FYI, ofa@github (pseudo mail anyway) is someone different from me! ... Used to be "Obama For America", now it's "Organize For Action".  This is why I use `<ofa-@github>` (with a `-` before the `@`).

If you could keep the orignal author in the commits that would be kind.

**Comment by jeevatkm** [comment]
Hello @ofa- , I use typically github squash & merge for PRs on all my repos and sometimes update commit message where necessary. 

**As for as my understanding it does not change author. I respect and value every author contributions.** 
screen shot 2018-02-10 at 9 16 44 am

This is what after squash & merge, as you can see "you're the actual committer and I'm the one merged into branch". 

Please mouse over or click on the user icon it takes to the profile https://github.com/ofa- I believe this is you. If you see; there is problem in your email address/ user id after the merge. I would surely believe some issue happening with Github merge process and it worth to report an issue to Github team.

**Comment by jeevatkm** [comment]
@ofa- Also you can see all your contributions to RWH plugin here -
https://github.com/jeevatkm/ReplyWithHeaderMozilla/commits?author=ofa-

And this is mine-
https://github.com/jeevatkm/ReplyWithHeaderMozilla/commits?author=jeevatkm

Your commits doesn't show up on my track.

**Comment by ofa-** [comment]
@jeevatkm yes, sorry if my message was miss-leading or sounded offensive.  I mean the author in the raw commit.  I know there is no problem with the tracking on github per-se, as you show above.  All is fine there.  It(s when you do a `git show` from the command line.

You are probably right, the pseudo email I use in my git config for `author.email` might cause issues with the github merge stuff.  I'll try to see with them.

**Comment by jeevatkm** [comment]
@ofa- No worries. I value your contributions and I explained in detail for understating purpose. I'm glad we are on the same page. 

Please report an issue with Github team for the email address.

**Comment by ofa-** [comment]
Talked to support@github.com.  Turns out the `email` used as author to create the squash-commit is taken from the PR author's profile > primary email, which in my case is set to `ofa@github` - since ages.

Now, email policy has changed, so I cannot set my primary email to `ofa-@github` (deemed invalid and not verifiable).  Maybe they can add the hyphen in their DB :)

**Comment by jeevatkm** [comment]
@ofa- Thanks for the update, I will be following up with them further.

**Comment by ofa-** [comment]
@jeevatkm I suspect it is going to be too complicated to update this email; I told them "ok, thanks, forget about it, I am fine with the current situation".  At least now we know why and how.  Sorry about he fuss.

**Pull request merged**
