### PR TITLE
Dual languages locale drop-down

### PR DESCRIPTION
**Pull request by ofa-**
Add dual-language "locale" drop-down labels (suggested by @Valerie-Yuuki)

Updated "lang" labels:
- `fr  de  es  ar  jp`   (Valerie-Yuuki)
- `pl pt` (ofa-)

### CODE REVIEW

**Comment by ofa-** [comment]
@jeevatkm if you can please use a plain or rebase merge there (instead of a squash), the different original author info will be preserved.

**Comment by ofa-** [comment]
Note: I would understand if you chose to not approve this PR, as I see it impacts the overall width and look of the "locale" drop-down.

**Comment by ofa-** [comment]
@jeevatkm gimme 2 secs, I'll rebase and update the PR - you merged the Portugese translations first, so this causes conflicst

**Comment by jeevatkm** [comment]
@ofa- Thank you 😄

**Comment by ofa-** [comment]
@jeevatkm I compacted the PR.  If you merge, please use a plain - or rebase - merge there (instead of a squash), so that the different original author info is preserved.

**Comment by jeevatkm** [comment]
@ofa- Did a rebase and merge 😄

**Pull request merged**
