### PR TITLE
Add zh_CN

### PR DESCRIPTION
**Pull request by DaduCC**

### CODE REVIEW

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@DaduCC Thanks for the PR. 
Can you remove the empty space after the `:` on header labels?

**Comment by DaduCC** [comment]
> @DaduCC Thanks for the PR. Can you remove the empty space after the `:` on header labels?

I've thought about this before, but Chinese punctuation is different from English punctuation, such as commas, periods, colons, single and double quotes. It's better to use the same syntax as the context in Chinese emails.

**Comment by jeevatkm** [comment]
@DaduCC It is better to confirm than to assume. Do you mean Chinese emails has two space after the colon? Because RWH does add one space.

**Comment by DaduCC** [comment]
> @DaduCC It is better to confirm than to assume. Do you mean Chinese emails has two space after the colon? Because RWH does add one space.

Chinese character is encoded in two bytes and associated with [full-width characters](https://en.wikipedia.org/wiki/Full-width_character). In Unicode, "：" (U+FF1A) looks wider than the  ":" (U+003A), I didn't add any space after the colon.

**Comment by jeevatkm** [comment]
@DaduCC Thank you for the details.

**Review by jeevatkm — APPROVED** [review]

**Comment by jeevatkm** [comment]
@DaduCC I have created a beta build for you.
[replywithheader-v2.7.0-beta.zip](https://github.com/jeevatkm/ReplyWithHeaderMozilla/files/12668118/replywithheader-v2.7.0-beta.zip)

**Comment by DaduCC** [comment]
@jeevatkm It work!

**Pull request merged**
