### PR TITLE
Add Japanese (jp) translations

### PR DESCRIPTION
**Pull request by ofa-**

### CODE REVIEW

**Comment by jeevatkm** [comment]
@ofa- Thanks for the PR.

**Comment by ofa-** [comment]
@jeevatkm thanks for the merge!  However, this is the work of @Valerie-Yuuki not mine ; can you make this commit hers ?

**Comment by ofa-** [comment]
(part of #12)

**Comment by jeevatkm** [comment]
@ofa- I'm not sure how GitHub handles the multi-level PR. Before merge this PR had a conflict. I have resolved and then did a merge.

We can revert this PR and @Valerie-Yuuki can created PR again. Please let me know I will revert it.

**Comment by ofa-** [comment]
@jeevatkm sorry for the induced merge; my plan was to rebase the "Japanese" PR before you merge but I failed to leave you a note to this effect.

To update the result of the merge, you can simply amend your last commit and push force:
```
git commit --amend \
  --author="Valerie-Yuuki <35336271+Valerie-Yuuki@users.noreply.github.com>" \
  --date="Mon Mar 19 11:39:49 2018 +0100"
git push -f
```

**Comment by jeevatkm** [comment]
@ofa- is that a correct user email id on github?

**Comment by ofa-** [comment]
yes, this is what is inside the original commit e469c4b (check it with git show)
That's a github feature, they provides that kind of user.email when user has no public email defined.

**Comment by jeevatkm** [comment]
@ofa- and @Valerie-Yuuki This is done.

**Comment by ofa-** [comment]
@jeevatkm cool, thanks!

**Comment by jeevatkm** [comment]
@ofa- Can you help me out with this? I need this complete for the Japanese locale to perform plain text email processing.

Plain Text email reply (tip: hold Shift key and press the Reply button)
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Pull request merged**
