### PR TITLE
Add date style (iso+full) support

### LINKED ISSUE #27: ISO Format Date, Local Time
Would be nice to have the option to use ISO format for the date (yyyy-MM-dd), though with local time instead of UTC.

### PR DESCRIPTION
**Pull request by ofa-**
- add prefs setting (Full or ISO date style)
- add support for date styling (parallel to time format setting)

Closes #27

### CODE REVIEW

**Comment by ofa-** [comment]
- I suggest doing a plain merge (no squash) this time :)

- potential future improvements (in separate PR):
  - change date "format" labels in prefs gui:
   Locale date format => Use local timezone
   International date format (GMT) => Use international time (GMT)
  - rename prefs properties:
   date.format => date.timezone
   date.style => date.format
   (will break existing settings)
  - use string properties (instead of int)
   and drop-downs instead of radio-buttons
   (would allow custom date/time format via config:)

**Comment by jeevatkm** [comment]
@ofa- Thanks for the PR and proposal. I will have a look.

I'm working on some internal improvements in the add-on.

**Comment by ofa-** [comment]
@jeevatkm about internal improvements, I have done this (not a PR yet) to uniformize the gui using styles:
https://github.com/jeevatkm/ReplyWithHeaderMozilla/compare/master...ofa-:uniformize+simplify_radiogroups?expand=1

**Comment by jeevatkm** [comment]
@ofa- Thank you for the PR. Merging it.

**Pull request merged**
