### PR TITLE
Split-out i18n to separate file rwh-i18n.js

### PR DESCRIPTION
**Pull request by ofa-**
- move i18n to separate file rwh-i18n.js
- import i18n in rwh-prefs.js and rwh.js

note: the imported module exposes global var 'i18n'

### CODE REVIEW

**Comment by ofa-** [comment]
Ooops, wait, issue with characters encoding on i18n'ed labels if using this PR.

**Comment by jeevatkm** [comment]
@ofa- Thank you for your PR.

**Comment by ofa-** [comment]
how about doing plain merge instead of squash ?

**Comment by ofa-** [comment]
note: alternative solution to import split-out `rwh-i18n.js`

https://github.com/jeevatkm/ReplyWithHeaderMozilla/compare/master...ofa-:alternative_import_of_rwh-i18n.js

**Comment by jeevatkm** [comment]
Do you prefer one over other? which one?

One of the important aspect of PR and squash merge is flexible to revert one commit (fix, enhancement, feature, etc.)instead of multiple commits.

**Pull request merged**
